//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONA()
        {
            this.TR_PERSONA_BANCO = new HashSet<TR_PERSONA_BANCO>();
        }
    
        public int ID_PERSONA { get; set; }
        public int ID_JEARQUIA { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public string ESTRATEGIA_LIDERI { get; set; }
        public string CVE_PROMOTOR { get; set; }
    
        public virtual CAT_JERARQUIA CAT_JERARQUIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_PERSONA_BANCO> TR_PERSONA_BANCO { get; set; }
    }
}
