//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PERSONA_BANCO
    {
        public Nullable<int> ID_PERSONA { get; set; }
        public Nullable<int> ID_BANCO { get; set; }
        public string CUENTA { get; set; }
    
        public virtual CAT_BANCO CAT_BANCO { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
    }
}
